language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  cargo: true
script:
  - cargo build --verbose
  - cargo test --verbose
  - cd ipfs-api; cargo build --verbose --features actix --no-default-features
  - cd ipfs-api; cargo test --verbose --features actix --no-default-features
